# Generated by Django 2.1.7 on 2019-03-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='github_link',
            field=models.CharField(default='https://www.github.com', max_length=50),
        ),
    ]
